train: ../datasets/dataYolov8/train/images
val: ../datasets/dataYolov8/val/images
test: ../datasets/dataYolov8/test/images

nc: 5

# Classes
names:
  0: 'car'
  1: 'pedestrian'
  2: 'trafficLight'
  3: 'truck'
  4: 'biker'